# Generated by Django 5.2.7 on 2025-12-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percentage')], max_length=20)),
                ('discount_value', models.IntegerField()),
                ('min_cart_value', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
