# Generated by Django 5.2.7 on 2025-12-05 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_usedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.coupon'),
        ),
    ]
