# Generated by Django 5.2.7 on 2025-12-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_payment_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
