# Generated by Django 5.2.7 on 2025-12-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_coupon_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='coupon',
            name='square_discount_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
