# Generated by Django 5.2.7 on 2025-12-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_coupon_is_locked_coupon_square_discount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
