# Generated by Django 5.2.7 on 2025-12-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_coupon_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
