# Generated by Django 5.2.7 on 2025-12-17 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_coupon_locked_at_coupon_locked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usedcoupon',
            unique_together={('user', 'coupon')},
        ),
    ]
