# Generated by Django 5.2.7 on 2025-12-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_alter_usedcoupon_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='locked_by',
        ),
    ]
